### ISSUE TITLE
boot.scr not work

### ISSUE THREAD

**Issue by Andrik45719** [gtxaspec/u-boot-ingenic#39]
```
## Executing script at 82000000
Wrong image format for "source" command
```
'boot.scr' file loaded into ${baseaddr} (80600000)
```
fatload mmc 0 ${baseaddr} boot.scr
```
but 'source' default address is 82000000

https://github.com/gtxaspec/u-boot-ingenic/blob/00945d092a930423708c43695af6a32fb583d27c/arch/mips/lib/board.c#L597
replace by
```C
	run_command("source ${baseaddr}", 0);
```

**Comment by gtxaspec** [comment]
fixed in https://github.com/gtxaspec/u-boot-ingenic/commit/4baf36633da4a8bfb833c7e37b604a7c2310badb
thank you so much!
